resources:
  - ../base


# namespace: goormthon-1 # fix me
# ArgoCD 사용 시 비워도 됩니다. 대신 ArgoCD 에서 namespace를 지정해 주세요.

images:
  - name: mongodb
    newTag: latest # change to the MongoDB version you want to use

patches:
  - target:
      kind: Secret
      name: mongodb-secret
    patch: |-
      - op: replace
        path: /stringData
        value:
          MONGO_INITDB_ROOT_USERNAME: goorm
          MONGO_INITDB_ROOT_PASSWORD: goorm123
          MONGO_INITDB_DATABASE: nollea

  - target:
       kind: Job
       name: mongosh
    patch: |-
       apiVersion: batch/v1
       kind: Job
       metadata:
         name: mongosh
       spec:
         template:
           spec:
             containers:
             - name: mongosh
               command:
               - /bin/bash
               - -c
               - |
                 mongosh "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongodb-0.mongodb.goormthon-4.svc.cluster.local:27017/admin" \
                 --eval 'db = db.getSiblingDB("nollea"); db.createCollection("init_check"); print("✅ myapp DB and collection created.");'