apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: goorm
  MONGO_INITDB_ROOT_PASSWORD: goorm123!
  # MONGO_INITDB_DATABASE: app-database