resources:
  - frontend.yaml
  - backend.yaml
  - ingress-front.yaml

configMapGenerator:
  - name: nollea-frontend-config #fix me
    files:
      - config.json=config/frontend-config.json

generatorOptions:
  disableNameSuffixHash: true