resources:
  - frontend.yaml
  - backend.yaml
  - ingress-front.yaml
  - ingress-backend.yaml

configMapGenerator:
  - name: nollea-frontend-config #fix me
    files:
      - config.json=config/frontend-config.json
#  - name: nollea-backend-config #fix me
#    files:
#      - config.json=config/backend-config.json

generatorOptions:
  disableNameSuffixHash: true