apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namespace: <team-name> # fix me

images:
  - name: mariadb
    newTag: lts-ubi # change to the mariaDB version you want to use 

patches:
  - target:
      kind: Secret
      name: mariadb-secret
    patch: |
      - op: replace
        path: /stringData
        value:
          MYSQL_USER: myuser
          MYSQL_PASSWORD: mypass123
          MYSQL_DATABASE: mydb